### ISSUE TITLE
KingDanger eval issue

### ISSUE THREAD

**Issue by robertomil81mil** [rosenthj/Winter#7] opened 2019-08-23 17:08 UTC
Hi Maki, I just watched a Winter vs Stockfish game and look at this
![IMG_201908235_120409](https://user-images.githubusercontent.com/51243949/63610238-9497ed00-c59e-11e9-9a1d-729a08254168.png)
Hopefully you can fix this. :-)

**Comment by tissatussa** [comment] 2020-11-16 11:16
do you mean Winter evalualates the position as -0.47 and SF is much more optimistic with +2.38 ?  I think this happens often with other engines also .. nothing spectacular, i guess it's NOT a bug .. later in the game Winter will conclude the position is much worse ..

**Comment by rosenthj** [comment] 2020-11-16 11:26
Yes, I agree this is probably not an actual bug, just Winter not seeing as deep or evaluating as well as the best in the world. I had wanted to look into this but at this point Winter is sufficiently changed from back when this was opened that I am closing this now.

**Closed by rosenthj** 2020-11-16 11:26 UTC

**Comment by robertomil81mil** [comment] 2020-11-16 16:28
Good job 👍
